#!/bin/bash

#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

playlists_dir=$HOME/.config/mpd/playlists/

if [ -z "$1" ]; then
    echo "Please specify the playlist names"
    ls -l $playlists_dir
else
    for playlist in "$@"; do
        # Check if playlist exists
        playlist_path=$playlists_dir$playlist.m3u
        if [ ! -f $playlist_path ]; then
            echo "Playlist $playlist not found!"
            exit 1
        fi

        echo "Downloading playlist: $playlist"

        # Create playlist dir to rsync files into
        mkdir -p $playlist
        cd $playlist
        rsync --progress --no-relative --files-from=$playlist_path root@jarvis:/srv/files/music/ ./

        # Go to $(cwd)
        cd ../
    done
fi

