#!/bin/bash

playlists_dir=$HOME/.config/mpd/playlists/

if [ -z "$1" ]; then
    echo "Please specify the playlist names"
    ls -l $playlists_dir
else
    for playlist in "$@"; do
        # Check if playlist exists
        playlist_path=$playlists_dir$playlist.m3u
        if [ ! -f $playlist_path ]; then
            echo "Playlist $playlist not found!"
            exit 1
        fi

        echo "Downloading playlist: $playlist"

        # Create playlist dir to rsync files into
        mkdir -p $playlist
        cd $playlist
        rsync --progress --no-relative --files-from=$playlist_path root@jarvis:/srv/files/music/ ./

        # Go to $(cwd)
        cd ../
    done
fi

