#!/bin/bash

# Get the current Mac address
ipLinkString=($(ip addr))

count=0
for element in "${ipLinkString[@]}"; do
    if [[ $element == "wlp"* ]]; then
        idLength=$(expr length $element)-1
        echo ${element:0:$idLength}
        break
    fi
    ((++count))
done

