#!/bin/bash

#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


case $1 in
    work)
#        for file in ~/.layout/work/*; do
#            index=${file//[^0-9]/}
#            i3-msg "workspace ${index}; append_layout ${file}"
#        done
        ~/.screenlayout/work.sh
        sleep 5
        i3-msg "[workspace=1] move workspace to output eDP-1"

        i3-msg "[workspace=2] move workspace to output HDMI-2"
        i3-msg "[workspace=7] move workspace to output HDMI-2"

        i3-msg "[workspace=3] move workspace to output DP-2"
        i3-msg "[workspace=9] move workspace to output DP-2"
        i3-msg "[workspace=10] move workspace to output DP-2"
    ;;
    *)
#        for file in ~/.layout/normal/*; do
#            index=${file//[^0-9]/}
#            i3-msg "workspace ${index}; append_layout ${file}"
#        done
    ;;
esac
