#!/bin/bash

case $1 in
    work)
#        for file in ~/.layout/work/*; do
#            index=${file//[^0-9]/}
#            i3-msg "workspace ${index}; append_layout ${file}"
#        done
        ~/.screenlayout/work.sh
        sleep 5
        i3-msg "[workspace=1] move workspace to output eDP-1"

        i3-msg "[workspace=2] move workspace to output HDMI-2"
        i3-msg "[workspace=7] move workspace to output HDMI-2"

        i3-msg "[workspace=3] move workspace to output DP-2"
        i3-msg "[workspace=9] move workspace to output DP-2"
        i3-msg "[workspace=10] move workspace to output DP-2"
    ;;
    *)
#        for file in ~/.layout/normal/*; do
#            index=${file//[^0-9]/}
#            i3-msg "workspace ${index}; append_layout ${file}"
#        done
    ;;
esac
