#!/bin/env python3
import os
import sys
import subprocess
from pueue.daemon.queue import Queue
from pueue.client.factories import command_factory

host = 'root@jarvis'


def main():
    try:
        subprocess.run(f"rsync {host}:~/.config/pueue/queue /tmp", shell=True, check=True)
        queue = Queue('/tmp')
        queue.read()
        data = queue.queue
        if len(data) == 0:
            print('Queue is empty')
        else:
            # get last 4 keys from status list
            keys = sorted(data.keys())
            status_list = []
            first = None
            for index, key in enumerate(keys):
                if data[key]['status'] == 'running':
                    first = index
                    break

            # Find first and last index for pueue list
            first = first if (first is not None) else len(keys)-4
            last = first+4
            # Last index is bigger than list
            # Set last to biggest index and first to last-4
            if last > len(keys):
                last = len(keys)
                first = last-4
                # First is smaller than 0. Set to 0
                if first < 0:
                    first = 0

            # Get the status of selected entries
            for key in reversed(keys[first:last]):
                entry_status = data[key]['status']
                status_list.append(("{}: {}".format(key, entry_status)))
            print(', '.join(status_list))

    except KeyboardInterrupt:
        sys.exit(0)


if __name__ == "__main__":
    main()
