#!/bin/bash

pkglist=$HOME/.setup/pkglist
tmp=.tmp

if [ -z "$1" ]; then
    echo "Please specify at least one package"
else
    for package in "$@"; do
        sudo pacman -Rns $package --noconfirm
        if [ $? -ne 0 ]; then
            echo "$package not found"
        else
            grep -x $package $pkglist
            if [ $? -eq 0 ]; then
                echo "nextGrep"
                grep -xv $package $pkglist > $pkglist$tmp
                #mv $pkglist$tmp $pkglist
                echo "$package removed from pkglist"
            else
                echo "$package not in pkglist"
            fi
        fi
    done
fi

