#!/bin/sh

#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

#1. Parameter: Workspace(s)
#2. Parameter: Sleep time
#3. Parameter: Quality

#Example: wscreenshot 1,2,3 5 100

resolution_x=1920
resolution_y=1080
outresolution_x=1920
outresolution_y=1080

workspaces=$(echo $1 | tr "," "\n")
sleeptime=${2:-5}
quality=${3:-100}

allowed_spaces=()
for space in $workspaces; do
    allowed_spaces+=('"current_workspace":"'$space'"')
done

echo "Quality: $quality"
echo "Sleeping for $sleeptime seconds"

while true; do
    output=$(i3-msg -t "get_outputs")
    lack_active=$(ps -aux | grep  i3-lock | wc -l)
    name=$(date +%Y-%m-%d-%H%M%S_${resolution_x}x${resolution_y}_scrot.png)
    outname=$(date +%Y-%m-%d-%H%M%S_${outresolution_x}x${outresolution_y}_scrot.png)

    on_screen=false
    for space in "${allowed_spaces[@]}"; do
        grep -q "$space" <<< "$output"
        if [[ $? -eq 0 ]] ; then
            on_screen=true
            break
        fi
    done
    # Actually do the screenshot
    # Move the screenshot to /tmp/ in case
    # it should be cropped later
    if [[ $lock_active -eq 1  ]]; then
        echo "On worspace, but i3 lock is active"
    elif [ "$on_screen" == false ]; then
        echo "Not on specified Workspaces"
    elif [ "$on_screen" == true ]; then
        scrot -q $quality $name
        # Cropping file to specified screen
        if [ "$4" == "down" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+$(($resolution_y - $outresolution_y)) $outname
        elif [ "$4" == "up" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+0 $outname
        elif [ "$4" == "left" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+0 $outname
        elif [ "$4" == "right" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+$(($resolution_x - $outresolution_x))+0 $outname
        fi

        # Cleanup of temporary file
        if [ -n "$4" ]; then
            rm $name
        fi
    fi
    sleep $sleeptime
done
