#!/bin/sh

#1. Parameter: Sleep time
#2. Parameter: Quality
#3. Parameter: Workspace(s)

#Example: wscreenshot 5 100 1,2,3

resolution_x=1920
resolution_y=1080
outresolution_x=1920
outresolution_y=1080

sleeptime=${1:-5}
quality=${2:-100}
workspaces=$(echo $3 | tr "," "\n")

allowed_spaces=()
for space in $workspaces; do
    allowed_spaces+=('"current_workspace":"'$space'"')
done

echo "Quality: $quality"
echo "Sleeping for $sleeptime seconds"

while true; do
    output=$(i3-msg -t "get_outputs")
    lock_active=$(ps -aux | grep  i3lock | wc -l)
    name=$(date +%Y-%m-%d-%H%M%S_${resolution_x}x${resolution_y}_scrot.png)
    outname=$(date +%Y-%m-%d-%H%M%S_${outresolution_x}x${outresolution_y}_scrot.png)

    on_screen=false
    for space in "${allowed_spaces[@]}"; do
        grep -q "$space" <<< "$output"
        if [[ $? -eq 0 ]] ; then
            on_screen=true
            break
        fi
    done
    # Actually do the screenshot
    # Move the screenshot to /tmp/ in case
    # it should be cropped later
    if [[ $lock_active -gt 1  ]]; then
        echo "On worspace, but i3 lock is active"
    elif [ "$on_screen" == false ]; then
        echo "Not on specified Workspaces"
    elif [ "$on_screen" == true ]; then
        scrot -q $quality $name
        # Cropping file to specified screen
        if [ "$4" == "down" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+$(($resolution_y - $outresolution_y)) $outname
        elif [ "$4" == "up" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+0 $outname
        elif [ "$4" == "left" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+0+0 $outname
        elif [ "$4" == "right" ]; then
            convert $name -crop ${outresolution_x}x${outresolution_y}+$(($resolution_x - $outresolution_x))+0 $outname
        fi

        # Cleanup of temporary file
        if [ -n "$4" ]; then
            rm $name
        fi
    fi
    sleep $sleeptime
done
