[theme]
theme = "modern"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
json = true
command = "~/.cache/cargo/bin/print_todo ~/Syncthing/Transfer/todo.md"
watch_files = ["/home/nuke/Syncthing/Transfer/todo.md"]

[[block]]
block = "disk_space"
path = "/"
format = "$icon $available"
alert_unit = "GB"
warning = 50.0
alert = 25.0

[[block]]
block = "custom"
command = "~/.cache/cargo/bin/netinfo"

[[block]]
block = "memory"
format = "$icon Mem: $mem_used_percents "

[[block]]
block = "cpu"
format = "$icon $barchart $utilization "
interval = 3

[[block]]
block = "hueshift"
step = 50
hue_shifter = "redshift"
format = " $temperature"
#{% if profile == "laptop" %}
[[block]]
block = "backlight"
format = " $icon $brightness"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
missing_format = ""
format = " $icon Bat0: $percentage $time "

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
missing_format = ""
format = " $icon Bat1: $percentage $time "
#{%- endif %}

[[block]]
block = "music"
player = "spotify"
format = " $icon  {$combo.str(max_w:25,rot_interval:0.5) $prev $play $next|}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "forward"
action = "next"
[[block.click]]
button = "back"
action = "prev"

[[block]]
block = "sound"
step_width = 2

[[block]]
block = "custom"
cycle = ["~/.bin/keyboard-layout en", "~/.bin/keyboard-layout de"]
interval = "once"
json = true

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d-%m-%y %T', l:de_DE) "
interval = 5
