theme = "modern"
icons = "awesome"

[[block]]
block = "custom"
command = "~/.cache/cargo/bin/print_todo ~/Syncthing/Transfer/todo.md"

[[block]]
block = "disk_space"
path = "/"
alias = "root:"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
command = "~/.cache/cargo/bin/netinfo"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "Mem: {mem_used_percents}"
clickable = false

[[block]]
block = "cpu"
format = "{barchart} {utilization}"
interval = 3
info = 80
warning = 90
critical = 95

[[block]]
block = "hueshift"
step = 50
hue_shifter = "redshift"

{% if profile == "laptop" -%}
[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat0: {percentage} {time}"

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat1: {percentage} {time}"

{%- endif %}

[[block]]
block = "music"
player = "spotify"
max_width = 15
marquee = true
marquee_interval = 10
marquee_speed = 0.25
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"
step_width = 2

[[block]]
block = "custom"
cycle = ["~/.bin/keyboard-layout en", "~/.bin/keyboard-layout de"]
interval = "once"
json = true

[[block]]
block = "time"
format = "%a %d-%m-%y %T"
interval = 5
