[profiles.pc]
posthooks = [
  "systemctl --user daemon-reload",
  "systemctl --user enable --now pueued",
  "systemctl --user enable --now ssh-agent",
  "systemctl --user enable --now dotfile-deploy",
  "systemctl --user enable --now mpd.socket",
  #"systemctl --user enable --now polizei",
]

#----- Setup for pc machines -----
[profiles.pc.dots]
zshenv = { source = "pc/zshenv", target = ".zshenv" }

# System config
user-dirs = { source = "pc/user-dirs.dirs", target = ".config/user-dirs.dirs" }
pueued_service = { source = "pc/systemd_user/pueued.service", target = ".config/systemd/user/pueued.service" }
ssh_agent_service = { source = "pc/systemd_user/ssh-agent.service", target = ".config/systemd/user/ssh-agent.service" }
dotfile_service = { source = "pc/systemd_user/dotfile-deploy.service", target = ".config/systemd/user/dotfile-deploy.service" }
polizei = { source = "pc/systemd_user/polizei.service", target = ".config/systemd/user/polizei.service" }
syncthing = { source = "pc/systemd_user/syncthing.service.d", target = ".config/systemd/user/syncthing.service.d" }

[profiles.desktop]
posthooks = ["systemctl --user daemon-reload"]
