# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = ".dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
vars = ["vars/vars.toml"]
# An array of post install shell commands
posthooks = []

[profiles.laptop]
extra_profiles = ["pc"]
vars = ["vars/laptop-vars.toml"]
prehooks = ["bash -c \"mkdir -p ~/.config/systemd/user/default.target.wants\""]

[profiles.desktop]
extra_profiles = ["pc"]
vars = ["vars/desktop-vars.toml"]

#----- Base setup for all machines -----
[settings.dots]
# Dotfile meta
post-merge-hook = { source="base/git-hook", target=".dotfiles/.git/hooks/post-merge" }
post-rewrite-hook = { source="base/git-hook", target=".dotfiles/.git/hooks/post-rewrite" }

# Shell
zsh = { source="base/zsh", target=".config/zsh" }
tmux = { source="base/tmux", target=".config/tmux" }
starship = { source="base/starship.toml", target=".config/starship.toml" }

# Tooling
git = { source="base/git", target=".config/git" }
pueue_aliases = { source="base/pueue", target=".config/pueue" }
pacman = { source="base/pacman", target=".config/pacman" }
nvim = { source="base/nvim", target=".config/nvim" }

# Language tooling
flake = { source="base/flake8", target=".config/flake8" }
npm = { source="base/npm", target=".config/npm" }

[profiles.pc]
prehooks = ["bash -c \"mkdir -p ~/.config/systemd/user/default.target.wants\""]
posthooks = [
  "systemctl --user daemon-reload",
  "systemctl --user enable pueued",
  "systemctl --user enable ssh-agent",
]

#----- Setup for pc machines -----
[profiles.pc.dots]
# Env
zshenv = { source="pc/zshenv", target=".zshenv" }

# System config
user-dirs = { source="pc/user-dirs.dirs", target=".config/user-dirs.dirs" }
pueued_service = { source="pc/systemd_user/pueued.service", target=".config/systemd/user/pueued.service" }
ssh_agent_service = { source="pc/systemd_user/ssh-agent.service", target=".config/systemd/user/ssh-agent.service" }

# pc core
i3 = { source="pc/i3", target=".config/i3" }
i3status-rust = { source="pc/i3status-rust", target=".config/i3status-rust" }
x11 = { source="pc/X11", target=".config/X11" }
xprofile = { source="pc/xprofile", target=".xprofile" }
dunst = { source="pc/dunstrc", target=".config/dunstrc" }

# pc Apps
rofi = { source="pc/rofi", target=".config/rofi" }
rofi-pass = { source="pc/rofi-pass", target=".config/rofi-pass" }
alacritty = { source="pc/alacritty", target=".config/alacritty" }
termite = { source="pc/termite/config", target=".config/termite" }

# Cli Apps
game_saver = { source="pc/game_saver.toml", target=".config/game_saver.toml" }

[profiles.server]
vars = ["vars/server-vars.toml"]

#----- Setup for server machines -----
[profiles.server.dots]
zshenv = { source="server/zshenv", target=".zshenv" }
