alacritty_fontsize = "5.5"

i3status_backlight = """
[[block]]
block = "backlight"
"""
i3status_battery = """
[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat0: {percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat1: {percentage}% {time}"
"""
