sync_address = "http://10.0.1.1:8888"
sync_frequency = "10m"
style = "compact"
show_preview = true
history_filter = [
  # Day-to-day shell commands
  "^cd .*",
  "^cd$",
  "^fg",
  "^j .*",
  "^ls",
  "^la",
  "^mv .*",

  # Git related
  "^gb",
  "^gb -D.*",
  "^git add .*",
  "^git branch -D*",
  "^gi t.*",
  "^git commit --fixup=.*",
  "^gsh",
  "^gls",
  "^gpuf?",
  "^glg",
  "^gsm",

  # Uninteresting commands
  "^curl .*",
  "^rsync .*",
  "^pong",
  "^t .*",
  "^td .*",
  "^nvim",
  "^wget .*",
  "^p .*",
  "^pad .*",

  # Typos
  "^a$",
  "^#.*",

  # Help text commands
  "^.* -h.*$",
  "^.* --help.*$",

  # Scripts/aliase
  "^km",
  "^kd",
]

[sync]
# Enable sync v2
# Run `atuin history init-store` when mitgrating from old sync
records = true
