sync_address = "http://10.0.1.1:8888"
sync_frequency = "10m"
style = "compact"
show_preview = true
history_filter = [
   "^a$",
   "^cd$",
   "^fg",
   "^j .*",
   "^ls",
   "^la",
   "^km",
   "^kd",
   "^t .*",
   "^td .*",
   "^pong",
   "^nvim",
   "^gb",
   "^gb -D.*",
   "^git add .*",
   "^git diff .*",
   "^git branch -D*",
   "^gi t.*",
   "^git commit --fixup=.*",
   "^gsh",
   "^gls",
   "^gpuf",
   "^gsm",
   "^cd .*",
   "^mv .*",
   "^wget .*",
   "^curl .*",
   "^rsync .*",
   "^#.*",
]
