sync_address = "http://10.0.1.1:8888"
sync_frequency = "10m"
style = "compact"
show_preview = true
history_filter = [
   "^t .*",
   "^td .*",
   "^j .*",
   "^ping .*",
   "^nvim",
   "^gls",
   "^git add .*",
   "^git diff .*",
   "^cd .*",
   "^mv .*",
   "^wget .*",
   "^curl .*",
   "^rsync .*",
   "^gb -D*",
   "^git branch -D*",
   "^spacman .*",
   "^#.*",
]
