#!/bin/bash
#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.



path=/sys/class/backlight/intel_backlight/brightness
maxBright=$(cat /sys/class/backlight/intel_backlight/max_brightness)
current=$(cat $path)

if [ "$1" == "up" ]; then
    new=$(($current+20))
    sudo tee $path <<< $new
elif [ "$1" == "down" ]; then
    new=$(($current-20))
    sudo tee $path <<< $new
elif [ "$1" == "max" ]; then
    sudo tee $path <<< $maxBright
else
    re='^[0-9]'
    if ! [[ $1 =~ $re ]] ; then
       echo "error: Not a number" >&2; exit 1
       exit 1
    fi
    sudo tee $path <<< $1
fi
