#!/bin/bash
# A script that creates a backup off all important files to my server

zip -r --encrypt /tmp/dokumente.zip ~/Dokumente
rsync --progress /tmp/dokumente.zip nuke@jarvis:backup/
rm /tmp/dokumente.zip

zip -r --encrypt /tmp/thunderbird.zip ~/.thunderbird
rsync --progress /tmp/thunderbird.zip nuke@jarvis:backup/
rm /tmp/thunderbird.zip

zip -r --encrypt /tmp/images.zip ~/Seafile/Bilder
rsync --progress /tmp/images.zip nuke@jarvis:backup/
rm /tmp/images.zip
