#!/bin/bash

if [ "$1" == "save" ]; then
    sudo tpacpi-bat -v -s startThreshold ${2:-0} 70
    sudo tpacpi-bat -v -s stopThreshold ${2:-0} 80
elif [ "$1" == "charge" ]; then
    sudo tpacpi-bat -v -s startThreshold ${2:-0} 100
    sudo tpacpi-bat -v -s stopThreshold ${2:-0} 100
fi
