#!/bin/bash

#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

pkglist=$HOME/.setup/pkglist
tmp=.tmp

if [ -z "$1" ]; then
    echo "Please specify at least one package"
else
    for package in "$@"; do
        sudo pacman -Rns $package --noconfirm
        if [ $? -ne 0 ]; then
            echo "$package not found"
        else
            grep -x $package $pkglist
            if [ $? -eq 0 ]; then
                echo "nextGrep"
                grep -xv $package $pkglist > $pkglist$tmp
                #mv $pkglist$tmp $pkglist
                echo "$package removed from pkglist"
            else
                echo "$package not in pkglist"
            fi
        fi
    done
fi

