#!/bin/bash

#The MIT License (MIT)
#Copyright (c) 2015 Arne Beer
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


# Interface that should be spoofed
interface=wlp4s0

# Get the current Mac address
ipLinkString=($(ip link show $interface))

count=0
for element in "${ipLinkString[@]}"; do
    if [[ $element == "link/ether" ]]; then
        echo "${ipLinkString[$count+1]}"
        currentMac="${ipLinkString[$count+1]}"
        break
    fi
    ((++count))
done

# Generating new random mac, first 3 bytes stay the
# same to ensure a correct vendor id
firstMac=$(echo $currentMac | head -c 8 )
lastMac=$(dd bs=1 count=3 if=/dev/random 2>/dev/null |hexdump -v -e '/1 ":%02X"')
mac=$firstMac$lastMac
mac=${mac,,}

# Stopping all networking and setting down interfaces
sudo netctl stop-all
sudo ip link set $interface down
sudo ip link set dev $interface down

# Changing mac address
sudo ip link set dev $interface address $mac
