# Path setup
path=($HOME/.bin $path)
path=($HOME/.cache/cargo/bin $path)
path=($HOME/work/utils/flutter/bin $path)
path=($HOME/work/bin $path)
path=($HOME/.cache/dart-pub-cache/bin $path)

# XDG Setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Tooling
export MANPAGER="bat -l man -p"
export EDITOR=nvim
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

# Application logic
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
export VAGRANT_EXPERIMENTAL="disks"
export JAVA_HOME=/usr/lib/jvm/default
export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

# Work/Android dev Stuff
export ANDROID_SDK_ROOT="$XDG_DATA_HOME/android-sdk"
path=($path $ANDROID_SDK_ROOT/cmdline-tools/latest/bin)
path=($path $ANDROID_SDK_ROOT/platform-tools)
path=($path $ANDROID_SDK_ROOT/tools)
export PUB_CACHE="$XDG_CACHE_HOME/dart-pub-cache"
export GRADLE_USER_HOME="$XDG_CACHE_HOME/gradle"
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure

# Styling
export GTK_THEME=Advaita:dark

# Convenience stuff
export VRC=$XDG_CONFIG_HOME/nvim/init.vim
export ZRC=$ZDOTDIR/.zshrc

# Config cleanup
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export MPLAYER_HOME=$XDG_CONFIG_HOME/mplayer
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export SQLITE_CONFIG="$XDG_CONFIG_HOME"/sqlite/sqliterc
export TASKRC=$XDG_CONFIG_HOME/task/taskrc
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export WEECHAT_HOME=$XDG_CONFIG_HOME/weechat
export XINITRC=$XDG_CONFIG_HOME/X11/xinitrc
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Cache cleanup
export CARGO_HOME=$XDG_CACHE_HOME/cargo
export CCACHE_DIR=$XDG_CACHE_HOME/ccache
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
export XARGO_HOME=$XDG_CACHE_HOME/cargo
export ZSH_COMPDUMP=$XDG_CACHE_HOME/zsh/zcompdump
export ANSIBLE_HOME="$XDG_CACHE_HOME/ansible"

# Data cleanup
export GOPATH=$XDG_DATA_HOME/go
export DISCORD_USER_DATA_DIR="${XDG_DATA_HOME}/discord"
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/password-store
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export VAGRANT_HOME=$XDG_DATA_HOME/vagrant
export VSCODE_EXTENSIONS=$XDG_DATA_HOME/vscode
export WINEPREFIX=$XDG_DATA_HOME/wine

# History files
export _FASD_DATA=$XDG_DATA_HOME/fasd/fasd_history
export HISTFILE=$XDG_DATA_HOME/zsh/history
export LESSHISTFILE="$XDG_DATA_HOME/less_history"
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history

# Runtime files
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
