#!/bin/python3
import json
from subprocess import Popen, PIPE


def main():
    process = Popen(["ip", "-j", "addr"], stdout=PIPE)
    (output, err) = process.communicate()
    exit_code = process.wait()

    devices = json.loads(output)

    for device in devices:
        # We aren't interested in the loopback device
        if device["ifname"] == "lo":
            continue

        # Device doesn't have an active connection.
        if len(device["addr_info"]) == 0:
            continue

        for addr in device["addr_info"]:
            # We want to see the ipv4 address
            if addr["family"] == "inet":
                name = device["ifname"]
                ip_addr = addr["local"]

                if name.startswith("e"):
                    symbol = ""
                elif name.startswith("w"):
                    symbol = ""

                print(f"{symbol} {name}: {ip_addr}")
                return

    print("No network")


main()
